/** US states + DC (full names, matches typical listing `state` values). */
export const US_STATES_FULL = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
] as const;

export const PROPERTY_TYPES = [
  "Single Family Home",
  "Condo / Townhome",
  "Apartment",
  "Commercial Space",
  "Estate",
  "Villa",
  "Mountain Lodge",
  "Beach House",
  "Wine Country Retreat",
  "Desert Oasis",
  "Penthouse",
  "Ski-in Ski-out",
] as const;

export const siteCopy = {
  legalName: "LuxPads",
  /** Public site domain label (no protocol) */
  domainDisplay: "LuxPads.co",
  domainUrl: "https://luxpads.co",
  tagline: "Directly Book Homes with Owner",
  marketplaceDisclaimer:
    "LuxPads is a listing marketplace. We do not process rental payments, hold security deposits, or finalize booking contracts. All agreements, payments, and stay logistics are between you and the homeowner.",
} as const;
